spring.application.name=taco-cloud
spring.thymeleaf.cache=false
spring.datasource.generate-unique-name=false
spring.datasource.name=tacocloud
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:postgresql://localhost:5432/taco_cloud
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.properties.hibernate.default_schema=PUBLIC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jmx.enabled=true
spring.data.rest.base-path=/data-api
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9000/oauth2/jwks
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=tacocloud-group
